name: generate json from php

on:
  push:
    branches:
      - generate
  schedule:
    - cron: "0 0 * * 3"

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: generate
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
      - name: Build
        run: |
          mkdir -p dist/api/kurs/
          fpname=$(php kurs.php)
          mv $fpname dist/api/kurs/
          cd dist/api/kurs/
          cp $fpname ../kurs.json
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
